version: '3.11'

services:
  django:
    build: .
    container_name: django
<<<<<<< HEAD
    command: python manage.py runserver 0.0.0.0:8000
=======
    command: gunicorn --bind 0.0.0.0:8000 mebel.wsgi
>>>>>>> 1d9f52e (Ready)
    ports:
      - '8000:8000'
    env_file:
      - ./.env
    environment:
      - DJANGO_DB_NAME=$DB_NAME
      - DJANGO_DB_USER=$DB_USER
      - DJANGO_DB_PASSWORD=$DB_PASSWORD
      - DJANGO_DB_HOST=$DB_HOST
      - DJANGO_DB_PORT=$DB_PORT
    volumes:
      - .:/app
<<<<<<< HEAD
      - static_volume:/home/itm1004/PycharmProjects/Mebel/static
      - media_volume:/home/itm1004/PycharmProjects/Mebel/media
=======
      - static_volume:/home/itm1004/PycharmProjects/mebel/static
      - media_volume:/home/itm1004/PycharmProjects/mebel/media
>>>>>>> 1d9f52e (Ready)
    depends_on:
      - db
      - redis

  db:
    image: postgres:15.3-alpine
    container_name: db
    ports:
      - '5432:5432'
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_HOST=$DB_HOST
      - POSTGRES_PORT=$DB_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data/
<<<<<<< HEAD
=======

>>>>>>> 1d9f52e (Ready)
  redis:
    image: redis:6-alpine
    volumes:
      - redis_data:/data/
    expose:
      - 6379

<<<<<<< HEAD
=======
  nginx:
    build: ./nginx
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - static_volume:/home/user/project_to_mebel/static/
      - media_volume:/home/user/project_to_mebel/media/
    ports:
      - "80:80"
    depends_on:
      - django

>>>>>>> 1d9f52e (Ready)
volumes:
  static_volume:
  media_volume:
  postgres_data:
  redis_data: