# Generated by Django 5.0.2 on 2024-03-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_currency_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=12)),
            ],
        ),
    ]
