# Generated by Django 5.0.2 on 2024-04-24 13:14

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_options_alter_currency_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=main.models.slugify_upload),
        ),
    ]
