# Generated by Django 5.0.2 on 2024-02-29 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='price',
            field=models.FloatField(verbose_name='Currency'),
        ),
    ]
